---
- name: Create ~/.mk-sbuild.rc
  copy:
    src: mk-sbuild.rc
    dest: /home/{{ ansible_user_id }}/.mk-sbuild.rc

- name: Create ~/.mk-sbuild.conf.lvm-snapshot
  copy:
    src: mk-sbuild.schroot.conf.lvm-snapshot
    dest: /home/{{ ansible_user_id }}/.mk-sbuild.schroot.conf.lvm-snapshot

- name: List existing chroots
  command: schroot --list --all-source-chroots
  register: existing_schroots

- name: Create chroot
  command: mk-sbuild {{ item|regex_replace('-.*', '') }} --arch={{ item|regex_replace('.*-', '') }}
  with_items: "{{ sbuild_chroots }}"
  when: "'source:%s' % item not in existing_schroots.stdout.split()"
