---
- name: Ensure no ephemeral disks are mounted
  mount:
    fstype: ext4
    name: /mnt
    src: /dev/{{ item }}
    state: absent
  with_items: "{{ sbuild_lvm_block_devices|default(ansible_devices.keys()) }}"
  when: sbuild_lvm_block_devices or item not in ('sda', 'xvda')

- name: Create VG
  lvg:
    vg: sbuild
    pvs: "{{ sbuild_lvm_block_devices|default(ansible_devices.keys())|map('regex_replace', '^', '/dev/')|join(',') }}"
  when: sbuild_lvm_block_devices or item not in ('sda', 'xvda')

- name: Create swap LV
  lvol:
    vg: sbuild
    lv: swap
    size: 5G

- name: Prepare swap LV
  command: mkswap /dev/sbuild/swap
  when: ansible_swaptotal_mb < 1

- name: Add swap LV to fstab
  mount:
    src: /dev/sbuild/swap
    fstype: swap
    name: none
    opts: sw
    state: present

- name: Mount swap LV
  command: swapon -a
  when: ansible_swaptotal_mb < 1

- name: Create build LV
  lvol:
    vg: sbuild
    lv: build
    size: 10G

- name: Prepare build LV
  filesystem:
    fstype: ext4
    dev: /dev/sbuild/build

- name: Add build LV to fstab
  mount:
    src: /dev/sbuild/build
    fstype: ext4
    path: /var/lib/sbuild/build
    state: mounted

- name: Set sbuild build dir permissions
  file:
    path: /var/lib/sbuild/build
    state: directory
    owner: sbuild
    group: sbuild
    mode: 02770
