---
- name: Update apt cache
  sudo: yes
  apt:
    update_cache: true
    cache_valid_time: 86400

- name: Install necessary packages
  sudo: yes
  apt:
    name: "{{ item }}"
  with_items:
    - nullmailer
    - debian-archive-keyring
    - lvm2
    - qemu-user-static
    - sbuild

- name: Install the Ubuntu archive keyring (in Debian)
  sudo: yes
  apt:
    name: ubuntu-archive-keyring
  when: ansible_distribution == "Debian"

- name: Install the Ubuntu archive keyring (in Ubuntu)
  sudo: yes
  apt:
    name: ubuntu-keyring
  when: ansible_distribution == "Ubuntu"

- name: Install nice-to-have packages
  sudo: yes
  apt:
    name: "{{ item }}"
  with_items:
    - bzr
    - bzr-builddeb
    - dput-ng
    - git
    - git-buildpackage
    - haveged
    - lintian
    - mercurial
    - mosh
    - screen
    - subversion
    - svn-buildpackage
    - tmux
    - vim-nox

# We use mk-sbuild:
- name: Install ubuntu-dev-tools
  sudo: yes
  apt:
    name: ubuntu-dev-tools
    install_recommends: false
