- name: Create VG
  lvg:
    vg: sbuild
    pvs: /dev/{{ item }}
  with_items: ansible_devices.keys()
  when: item not in ('sda', 'xvda')

- name: Create swap LV
  #lvol: vg=sbuild lv=swap size=5G
  lvol:
    vg: sbuild
    lv: swap
    size: 5G

- name: Prepare swap LV
  command: mkswap /dev/sbuild/swap
  when: ansible_swaptotal_mb < 1

- name: Add swap LV to fstab
  lineinfile:
    dest: /etc/fstab
    line: /dev/sbuild/swap none swap sw 0 0

- name: Mount swap LV
  command: swapon -a
  when: ansible_swaptotal_mb < 1
